version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'jonarro@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '80:80'
    depends_on:
      - db
